export const equipmentItems = [
  {
    id: "eq001",
    name: "Dumbbells",
    description:
      "Compact dumbbells with adjustable weights—perfect for strength training at home.",
    price: 120,
    rating: 4.8,
    tags: ["strength", "adjustable", "home"],
    image: "/images/equipments/dumbbell.webp",
    inStock: true,
  },
  {
    id: "eq002",
    name: "Yoga Mat",
    description: "Non-slip, thick yoga mat for all fitness levels.",
    price: 25,
    rating: 4.6,
    tags: ["flexibility", "floor", "stretching"],
    image: "/images/equipments/yogamat.webp",
    inStock: true,
  },
  {
    id: "eq003",
    name: "Resistance Bands",
    description:
      "Set of 5 bands for home workouts, rehab, and mobility training—portable and versatile.",
    price: 50,
    rating: 4.7,
    tags: ["strength", "rehab", "portable"],
    image: "/images/equipments/resistanceband.webp",
    inStock: true,
  },
  {
    id: "eq004",
    name: "Kettlebell",
    description:
      "Durable 15 lbs kettlebell for full-body strength and cardio training.",
    price: 60,
    rating: 4.5,
    tags: ["strength", "endurance", "versatile"],
    image: "/images/equipments/kettlebell.webp",
    inStock: false,
  },
  {
    id: "eq005",
    name: "Balance Ball",
    description:
      "Stability ball for core workouts, stretching, and posture training.",
    price: 28,
    rating: 4.4,
    tags: ["core", "balance", "rehab"],
    image: "/images/equipments/balanceball.webp",
    inStock: true,
  },
  {
    id: "eq006",
    name: "Jump Rope",
    description: "Adjustable speed rope for cardio and agility workouts.",
    price: 15,
    rating: 4.0,
    tags: ["cardio", "conditioning", "portable"],
    image: "/images/equipments/jumprope.webp",
    inStock: true,
  },
  {
    id: "eq007",
    name: "Foam Roller",
    description: "High-density roller for muscle recovery and massage.",
    price: 22,
    rating: 4.5,
    tags: ["recovery", "mobility", "rehab"],
    image: "/images/equipments/foamroller.webp",
    inStock: true,
  },
  {
    id: "eq008",
    name: "Barbell Set",
    description:
      "Standard bar and plates—ideal for weightlifting and power training.",
    price: 150,
    rating: 4.6,
    tags: ["strength", "powerlifting", "home"],
    image: "/images/equipments/barbell.webp",
    inStock: true,
  },
  {
    id: "eq009",
    name: "Pull-Up Bar",
    description:
      "Doorway pull-up bar with multiple grip positions for upper body strength training.",
    price: 35,
    rating: 4.2,
    tags: ["upper body", "strength", "bodyweight"],
    image: "/images/equipments/pullupbar.webp",
    inStock: false,
  },
  {
    id: "eq010",
    name: "Ankle Weights",
    description:
      "Adjustable 5 lb pair—adds resistance to walks or workouts for better mobility and strength.",
    price: 18,
    rating: 4.3,
    tags: ["legs", "resistance", "mobility"],
    image: "/images/equipments/ankleweight.webp",
    inStock: true,
  },
  {
    id: "eq011",
    name: "Stationary Bike",
    description:
      "Low-impact indoor cycling machine for endurance and fat burn.",
    price: 350,
    rating: 4.7,
    tags: ["cardio", "legs", "home gym"],
    image: "/images/equipments/stationarybike.webp",
    inStock: false,
  },
  {
    id: "eq012",
    name: "Mini Stepper",
    description: "Compact cardio machine to simulate stair climbing.",
    price: 80,
    rating: 3.6,
    tags: ["cardio", "lower body", "home"],
    image: "/images/equipments/ministepper.webp",
    inStock: true,
  },
  {
    id: "eq013",
    name: "Rowing Machine",
    description: "Low-impact full-body cardio and strength workout machine.",
    price: 499,
    rating: 4.7,
    tags: ["cardio", "full body", "home gym"],
    image: "/images/equipments/rowingmachine.webp",
    inStock: true,
  },
  {
    id: "eq014",
    name: "Gliding Discs",
    description: "Double-sided discs for strength and stability training.",
    price: 20,
    rating: 3.8,
    tags: ["core", "glutes", "portable"],
    image: "/images/equipments/glidingdiscs.webp",
    inStock: false,
  },
  {
    id: "eq015",
    name: "Weight Bench",
    description:
      "Sturdy adjustable bench for presses, rows, and full-body workouts.",
    price: 290,
    rating: 4.6,
    tags: ["strength", "upper body", "bench"],
    image: "/images/equipments/pressing-machine.webp",
    inStock: true,
  },
  {
    id: "eq016",
    name: "Battle Rope",
    description: "Durable rope for HIIT, strength, and endurance training.",
    price: 75,
    rating: 4.4,
    tags: ["conditioning", "arms", "HIIT"],
    image: "/images/equipments/battle-rope.webp",
    inStock: true,
  },
  {
    id: "eq017",
    name: "Treadmill",
    description: "Space-saving treadmill with multiple speed settings.",
    price: 820,
    rating: 4.8,
    tags: ["cardio", "indoor", "running"],
    image: "/images/equipments/treadmill.webp",
    inStock: true,
  },
  {
    id: "eq018",
    name: "Suspension Trainer",
    description:
      "TRX-style bodyweight system for building strength, balance, and mobility.",
    price: 110,
    rating: 4.6,
    tags: ["bodyweight", "core", "functional"],
    image: "/images/equipments/trx.webp",
    inStock: true,
  },
  {
    id: "eq019",
    name: "Push-Up Bars",
    description:
      "Ergonomic bars for deeper push-ups, better form, and wrist support.",
    price: 30,
    rating: 4.4,
    tags: ["upper body", "home", "portable"],
    image: "/images/equipments/pushupbars.webp",
    inStock: true,
  },

  {
    id: "eq020",
    name: "Medicine Ball",
    description:
      "10 lb ball for dynamic strength, coordination, and core training.",
    price: 45,
    rating: 4.5,
    tags: ["strength", "explosive", "core"],
    image: "/images/equipments/medecineball.webp",
    inStock: true,
  },
];
