export const equipmentItems = [
  {
    id: "eq001",
    name: "Dumbbells",
    description:
      "Compact and versatile dumbbells with adjustable weights — perfect for home or gym workouts. Build muscle, tone your arms, and enhance overall strength with ease. Suitable for beginners and advanced lifters alike.",
    price: 120,
    rating: 4.8,
    tags: ["strength", "adjustable", "home"],
    image: "/images/equipments/dumbbell.webp",
    inStock: true,
  },
  {
    id: "eq002",
    name: "Yoga Mat",
    description:
      "A thick, non-slip yoga mat that provides comfort and stability for every pose. Designed for all fitness levels, it supports yoga, pilates, and stretching sessions. Easy to roll and carry for home or studio use.",
    price: 25,
    rating: 4.6,
    tags: ["flexibility", "floor", "stretching"],
    image: "/images/equipments/yogamat.webp",
    inStock: true,
  },
  {
    id: "eq003",
    name: "Resistance Bands",
    description:
      "A complete set of 5 resistance bands for full-body workouts, mobility training, and rehabilitation. Lightweight and portable, they help improve strength, flexibility, and muscle tone anywhere you go.",
    price: 50,
    rating: 4.7,
    tags: ["strength", "rehab", "portable"],
    image: "/images/equipments/resistanceband.webp",
    inStock: true,
  },
  {
    id: "eq004",
    name: "Kettlebell",
    description:
      "Durable 15 lbs kettlebell for dynamic strength and cardio training. Ideal for swings, squats, and presses to build endurance, burn fat, and strengthen your entire body. A must-have for functional workouts.",
    price: 60,
    rating: 4.5,
    tags: ["strength", "endurance", "versatile"],
    image: "/images/equipments/kettlebell.webp",
    inStock: false,
  },
  {
    id: "eq005",
    name: "Balance Ball",
    description:
      "A stability ball designed for improving posture, core strength, and flexibility. Great for yoga, pilates, and physiotherapy. It adds fun and challenge to every workout routine.",
    price: 28,
    rating: 4.4,
    tags: ["core", "balance", "rehab"],
    image: "/images/equipments/balanceball.webp",
    inStock: true,
  },
  {
    id: "eq006",
    name: "Jump Rope",
    description:
      "An adjustable speed rope built for agility, coordination, and endurance. Ideal for cardio workouts, warm-ups, and HIIT sessions. Lightweight, tangle-free, and easy to carry anywhere.",
    price: 15,
    rating: 4.0,
    tags: ["cardio", "conditioning", "portable"],
    image: "/images/equipments/jumprope.webp",
    inStock: true,
  },
  {
    id: "eq007",
    name: "Foam Roller",
    description:
      "High-density foam roller for deep tissue massage and muscle recovery. Relieve soreness, improve blood circulation, and enhance flexibility after intense workouts or long days.",
    price: 22,
    rating: 4.5,
    tags: ["recovery", "mobility", "rehab"],
    image: "/images/equipments/foamroller.webp",
    inStock: true,
  },
  {
    id: "eq008",
    name: "Barbell Set",
    description:
      "A complete barbell and weight plate set for serious strength training. Ideal for squats, deadlifts, presses, and Olympic lifts. Built to last and designed for both home and commercial use.",
    price: 150,
    rating: 4.6,
    tags: ["strength", "powerlifting", "home"],
    image: "/images/equipments/barbell.webp",
    inStock: true,
  },
  {
    id: "eq009",
    name: "Pull-Up Bar",
    description:
      "Heavy-duty doorway pull-up bar with multiple grip options. Strengthen your back, arms, and core with ease. Easy to install and fits most door frames — no screws required.",
    price: 35,
    rating: 4.2,
    tags: ["upper body", "strength", "bodyweight"],
    image: "/images/equipments/pullupbar.webp",
    inStock: false,
  },
  {
    id: "eq010",
    name: "Ankle Weights",
    description:
      "Adjustable 5 lb ankle weights that add resistance to walks, runs, and workouts. Helps tone your legs, improve endurance, and enhance mobility with every step.",
    price: 18,
    rating: 4.3,
    tags: ["legs", "resistance", "mobility"],
    image: "/images/equipments/ankleweight.webp",
    inStock: true,
  },
  {
    id: "eq011",
    name: "Stationary Bike",
    description:
      "Low-impact indoor cycling machine designed for comfort and performance. Burn calories, improve stamina, and enjoy smooth pedalling with adjustable resistance levels.",
    price: 350,
    rating: 4.7,
    tags: ["cardio", "legs", "home gym"],
    image: "/images/equipments/stationarybike.webp",
    inStock: false,
  },
  {
    id: "eq012",
    name: "Mini Stepper",
    description:
      "Compact stair-stepping machine that provides an effective lower-body and cardio workout. Great for small spaces and daily fitness routines — strengthens legs and burns fat.",
    price: 80,
    rating: 3.6,
    tags: ["cardio", "lower body", "home"],
    image: "/images/equipments/ministepper.webp",
    inStock: true,
  },
  {
    id: "eq013",
    name: "Rowing Machine",
    description:
      "Full-body cardio and strength machine offering a smooth rowing motion. Targets arms, back, core, and legs simultaneously. Ideal for home gyms and total-body fitness.",
    price: 499,
    rating: 4.7,
    tags: ["cardio", "full body", "home gym"],
    image: "/images/equipments/rowingmachine.webp",
    inStock: true,
  },
  {
    id: "eq014",
    name: "Gliding Discs",
    description:
      "Dual-sided discs that glide on carpet or hard floors for core and stability workouts. Perfect for lunges, planks, and ab exercises — lightweight and easy to pack.",
    price: 20,
    rating: 3.8,
    tags: ["core", "glutes", "portable"],
    image: "/images/equipments/glidingdiscs.webp",
    inStock: false,
  },
  {
    id: "eq015",
    name: "Weight Bench",
    description:
      "A sturdy, adjustable bench designed for presses, rows, and strength training. Supports heavy loads and allows multiple angles for full-body workouts at home or in the gym.",
    price: 290,
    rating: 4.6,
    tags: ["strength", "upper body", "bench"],
    image: "/images/equipments/pressing-machine.webp",
    inStock: true,
  },
  {
    id: "eq016",
    name: "Battle Rope",
    description:
      "Heavy-duty rope built for HIIT, strength, and endurance training. Engage your arms, shoulders, and core while boosting cardiovascular health. Suitable for indoor and outdoor workouts.",
    price: 75,
    rating: 4.4,
    tags: ["conditioning", "arms", "HIIT"],
    image: "/images/equipments/battle-rope.webp",
    inStock: true,
  },
  {
    id: "eq017",
    name: "Treadmill",
    description:
      "Compact, foldable treadmill with multiple speed and incline settings. Perfect for home cardio sessions, from brisk walks to intense runs, with digital performance tracking.",
    price: 820,
    rating: 4.8,
    tags: ["cardio", "indoor", "running"],
    image: "/images/equipments/treadmill.webp",
    inStock: true,
  },
  {
    id: "eq018",
    name: "Suspension Trainer",
    description:
      "Professional-grade TRX-style suspension trainer for full-body workouts using your own weight. Improve balance, strength, and flexibility anywhere — from home to outdoors.",
    price: 110,
    rating: 4.6,
    tags: ["bodyweight", "core", "functional"],
    image: "/images/equipments/trx.webp",
    inStock: true,
  },
  {
    id: "eq019",
    name: "Push-Up Bars",
    description:
      "Ergonomic push-up bars that reduce wrist strain and improve form. Increase range of motion and build upper body strength effectively at home or in the gym.",
    price: 30,
    rating: 4.4,
    tags: ["upper body", "home", "portable"],
    image: "/images/equipments/pushupbars.webp",
    inStock: true,
  },
  {
    id: "eq020",
    name: "Medicine Ball",
    description:
      "Weighted 10 lb medicine ball for explosive strength, coordination, and core training. Great for partner workouts, circuits, and full-body conditioning exercises.",
    price: 45,
    rating: 4.5,
    tags: ["strength", "explosive", "core"],
    image: "/images/equipments/medecineball.webp",
    inStock: true,
  },
];
