export const equipmentItems = [
  {
    id: "eq001",
    name: "Adjustable Dumbbells",
    description:
      "Compact dumbbells with adjustable weights, perfect for home workouts.",
    price: 120,
    rating: 4.8,
    tags: ["strength", "adjustable", "home"],
    image: "https://via.placeholder.com/150?text=Adjustable+Dumbbells",
    inStock: true,
  },
  {
    id: "eq002",
    name: "Yoga Mat",
    description: "Non-slip, thick yoga mat for all fitness levels.",
    price: 25,
    rating: 4.6,
    tags: ["flexibility", "floor", "stretching"],
    image: "https://via.placeholder.com/150?text=Yoga+Mat",
    inStock: true,
  },
  {
    id: "eq003",
    name: "Resistance Bands Set",
    description:
      "Set of 5 resistance bands for home workouts, rehab, and mobility training.",
    price: 50,
    rating: 4.7,
    tags: ["strength", "rehab", "portable"],
    image: "https://via.placeholder.com/150?text=Resistance+Bands",
    inStock: true,
  },
  {
    id: "eq004",
    name: "Kettlebell (15 lbs)",
    description:
      "Durable kettlebell for full-body strength and cardio training.",
    price: 60,
    rating: 4.5,
    tags: ["strength", "endurance", "versatile"],
    image: "https://via.placeholder.com/150?text=Kettlebell",
    inStock: false,
  },
  {
    id: "eq005",
    name: "Balance Ball",
    description:
      "Stability ball for core workouts, stretching, and posture training.",
    price: 28,
    rating: 4.4,
    tags: ["core", "balance", "rehab"],
    image: "https://via.placeholder.com/150?text=Balance+Ball",
    inStock: true,
  },
  {
    id: "eq006",
    name: "Jump Rope",
    description: "Adjustable speed rope for cardio and agility workouts.",
    price: 15,
    rating: 4.3,
    tags: ["cardio", "conditioning", "portable"],
    image: "https://via.placeholder.com/150?text=Jump+Rope",
    inStock: true,
  },
  {
    id: "eq007",
    name: "Foam Roller",
    description: "High-density roller for muscle recovery and massage.",
    price: 22,
    rating: 4.5,
    tags: ["recovery", "mobility", "rehab"],
    image: "https://via.placeholder.com/150?text=Foam+Roller",
    inStock: true,
  },
  {
    id: "eq008",
    name: "Barbell Set (Standard)",
    description:
      "Includes bar and plates—ideal for weightlifting and power training.",
    price: 150,
    rating: 4.6,
    tags: ["strength", "powerlifting", "home"],
    image: "https://via.placeholder.com/150?text=Barbell+Set",
    inStock: true,
  },
  {
    id: "eq009",
    name: "Pull-Up Bar",
    description: "Doorway pull-up bar with multiple grip positions.",
    price: 35,
    rating: 4.4,
    tags: ["upper body", "strength", "bodyweight"],
    image: "https://via.placeholder.com/150?text=Pull-Up+Bar",
    inStock: false,
  },
  {
    id: "eq010",
    name: "Ankle Weights (5 lbs pair)",
    description:
      "Add resistance to your walks or workouts with adjustable ankle weights.",
    price: 18,
    rating: 4.3,
    tags: ["legs", "resistance", "mobility"],
    image: "https://via.placeholder.com/150?text=Ankle+Weights",
    inStock: true,
  },
  {
    id: "eq011",
    name: "Medicine Ball (10 lbs)",
    description:
      "Versatile tool for dynamic strength and coordination training.",
    price: 45,
    rating: 4.5,
    tags: ["strength", "explosive", "core"],
    image: "https://via.placeholder.com/150?text=Medicine+Ball",
    inStock: true,
  },
  {
    id: "eq012",
    name: "Mini Stepper",
    description: "Compact cardio machine to simulate stair climbing.",
    price: 80,
    rating: 4.2,
    tags: ["cardio", "lower body", "home"],
    image: "https://via.placeholder.com/150?text=Mini+Stepper",
    inStock: true,
  },
  {
    id: "eq013",
    name: "Rowing Machine",
    description: "Low-impact full-body cardio and strength workout machine.",
    price: 499.99,
    rating: 4.7,
    tags: ["cardio", "full body", "home gym"],
    image: "https://via.placeholder.com/150?text=Rowing+Machine",
    inStock: true,
  },
  {
    id: "eq014",
    name: "Gliding Discs",
    description: "Double-sided discs for strength and stability training.",
    price: 20,
    rating: 4.3,
    tags: ["core", "glutes", "portable"],
    image: "https://via.placeholder.com/150?text=Gliding+Discs",
    inStock: false,
  },
  {
    id: "eq015",
    name: "Bench Press Station",
    description: "Sturdy adjustable bench for pressing, rows, and more.",
    price: 290,
    rating: 4.6,
    tags: ["strength", "upper body", "bench"],
    image: "https://via.placeholder.com/150?text=Bench+Press",
    inStock: true,
  },
  {
    id: "eq016",
    name: "Battle Rope",
    description: "Durable rope for HIIT, strength, and endurance training.",
    price: 75,
    rating: 4.4,
    tags: ["conditioning", "arms", "HIIT"],
    image: "https://via.placeholder.com/150?text=Battle+Rope",
    inStock: true,
  },
  {
    id: "eq017",
    name: "Treadmill",
    description: "Space-saving treadmill with multiple speed settings.",
    price: 820,
    rating: 4.8,
    tags: ["cardio", "indoor", "running"],
    image: "https://via.placeholder.com/150?text=Treadmill",
    inStock: true,
  },
  {
    id: "eq018",
    name: "TRX Suspension Trainer",
    description: "Bodyweight training system for strength and mobility.",
    price: 110,
    rating: 4.6,
    tags: ["bodyweight", "core", "functional"],
    image: "https://via.placeholder.com/150?text=TRX+Trainer",
    inStock: true,
  },
  {
    id: "eq019",
    name: "Push-Up Bars",
    description: "Ergonomic bars for deep push-ups and joint support.",
    price: 30,
    rating: 4.4,
    tags: ["upper body", "home", "portable"],
    image: "https://via.placeholder.com/150?text=Push-Up+Bars",
    inStock: true,
  },
  {
    id: "eq020",
    name: "Stationary Bike",
    description:
      "Low-impact indoor cycling machine for endurance and fat burn.",
    price: 350,
    rating: 4.7,
    tags: ["cardio", "legs", "home gym"],
    image: "https://via.placeholder.com/150?text=Stationary+Bike",
    inStock: false,
  },
];
